### ISSUE TITLE
Explore Data Sources

### ISSUE THREAD

**Issue by c-flaherty** [justincohler/scoop#12]
See what data we can get:
- Facebook
- Instagram
- Yelp
- website (google analytics)

**Comment by c-flaherty** [comment]
# Yelp
- Yelp Fusion API provides business details such as photos, yelp rating, hours of operation, reviews, etc.
- Requesting more than 3 reviews at a time requires VIP (paid) version

**Comment by justincohler** [comment]
**Facebook**
- Business Manager API takes a Business ID and an Access Token gives you FB Page statistics
- Comments, reactions, post metadata
- Insights API (clicks, time spent, cost per click, unique impressions)
- This includes "Keyword Stats"

https://developers.facebook.com/docs/marketing-api/insights#query-for-statistics

**Comment by Dsolnik** [comment]
Google
Audience Metrics
https://developers.google.com/analytics/devguides/reporting/core/dimsmets#view=detail&group=audience
https://developers.google.com/analytics/devguides/reporting/core/dimsmets
